### ISSUE TITLE
width of intervals error

### ISSUE THREAD

**Issue by topape** [ahaselsteiner/virocon#128]
If the width of intervals is smaller than 1 the fit throws an error.  

Exception  website
<img width="724" alt="bildschirmfoto 2018-04-23 um 18 55 53" src="https://user-images.githubusercontent.com/34214376/39141486-3ff7da62-4728-11e8-9b81-61327745cbb1.png">

Exception terminal
<img width="1149" alt="bildschirmfoto 2018-04-23 um 18 58 22" src="https://user-images.githubusercontent.com/34214376/39141539-61dcf9fa-4728-11e8-98a3-1105258980bf.png">

**Comment by janlehmk** [comment]
The problem was that the centers were deleted while there was a loop at the centers so it raises an IndexError. There is a solution in a Pull Request there the centers will be deleted after the loop.

**Comment by janlehmk** [comment]
Done.
