### ISSUE TITLE
selected-file-information

### ISSUE THREAD

**Issue by topape** [ahaselsteiner/virocon#136]
**I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] code improvement request

## Expected behavior
**How should it work (with the bug fixed or the feature implemented)?**
if a measurement file is selected the information should be shown to the user.

**Screenshot**
![image](https://user-images.githubusercontent.com/11452055/39254580-af202056-48aa-11e8-9211-7fa5020c5fc3.png)

## Actual behavior
**How does it currently work (with the bug causing problems or without the feature)?**
the information is not shown. 

**Screenshot**

## Steps to reproduce the problem (how to see the actual behavior)

  1. go to file upload page
  2. click browse to select a file to upload

**Comment by ahaselsteiner** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/11452055/39367924-75e0c978-4a38-11e8-93e7-085d60f53955.png)
