### ISSUE TITLE
mu function and sigma function are equal

### ISSUE THREAD

**Issue by ghost** [ahaselsteiner/virocon#172]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] code improvement request

## Expected behavior
**How should it work (with the bug fixed or the feature implemented)?**
After a measure file fit we should get from the multivariate distribution the scale function and not the mu-function for the plots. 

**Screenshot**

## Actual behavior
**How does it currently work (with the bug causing problems or without the feature)?**
After a fit we got the mu-function though we called the scaled function. 
Furthermore the fits aren't right. The distribution does not match the shown histogram.
The error only appears for the fowling settings for the second variable 
<img width="677" alt="bildschirmfoto 2018-05-14 um 19 23 57" src="https://user-images.githubusercontent.com/34214376/40048249-0933a2de-5832-11e8-80bc-bc2464360419.png">
 

**Screenshot**
Printed the called scale function into the console ( It's equal to the mu function) 
<img width="681" alt="bildschirmfoto 2018-05-14 um 19 23 30" src="https://user-images.githubusercontent.com/34214376/40048091-9d5d7dfa-5831-11e8-9dcf-1671f6b59b00.png">

mu-function in the latex report for the fit
<img width="454" alt="bildschirmfoto 2018-05-14 um 19 23 39" src="https://user-images.githubusercontent.com/34214376/40048149-c75f70cc-5831-11e8-9ba9-09c6c67feeec.png">

## Steps to reproduce the problem (how to see the actual behavior)

  1. upload measure file (vanem)
  2. fit probabilistic model with the settings in the screenshot above.
  3. inspect the fit results or  you can see a type error (it depends on the status of your current branch)

**Comment by ahaselsteiner** [comment]
This bug report describes the same bug as #171 . When working on it I will reference #171.
