### ISSUE TITLE
Delete unnecessary requirements in requirements.txt

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#23]
Otherwise building takes forever:

![image](https://user-images.githubusercontent.com/11452055/32851646-d08469c6-ca35-11e7-885a-71e105941d66.png)

**Comment by kawindme** [comment]
https://docs.travis-ci.com/user/caching/#pip-cache describes how to speed up the build by caching the required python packages.
requirements.txt should still be cleaned.
