### ISSUE TITLE
Adapt all compute imports to new project structure (examples in the documentation seem to be not adapted yet)

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#28]
Here pycharm warns that compute is an unresolved reference (similar to the problems that we had in the "normal" part of the code):

![image](https://user-images.githubusercontent.com/11452055/32957246-6e3866d2-cbbb-11e7-805c-8ea69e3b676d.png)

Kai, can you take a look at this?

**Comment by kawindme** [comment]
Import in Docu, use the standard way to import a package. This should not be changed. Instead the compute package should be made installable. see #47
