### ISSUE TITLE
Think about removing the logo since it takes a lot of space

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#37]
![image](https://user-images.githubusercontent.com/11452055/33275669-a7b4074c-d393-11e7-9f9e-36b8fb7ee161.png)

**Comment by ahaselsteiner** [comment]
Result of team discussion: We will remove the logo from the the sites, which deal with the computation, and where it adds little information but takes away space. For the other sites, we have not decided yet. This issue is related to #92

**Comment by topape** [comment]
Result of second team discussion: We will remove the loge form each site. Perhaps we will design a index site with the virocon logo.
