### ISSUE TITLE
Write correct imprint

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#46]
![image](https://user-images.githubusercontent.com/11452055/33549516-1881ce26-d8eb-11e7-9cb1-6e848d6dc6fb.png)

Also clarify if there are images from pixabay (??).

**Comment by janlehmk** [comment]
@ahaselsteiner How about this?
![imprint](https://user-images.githubusercontent.com/23475763/35520541-99db9198-0517-11e8-981d-5f1a3b80ff22.JPG)

**Comment by janlehmk** [comment]
Pull Request ist merged
