### ISSUE TITLE
Use virocon@uni-bremen.de as email server

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#50]
Currently a gmx email address is used:

![image](https://user-images.githubusercontent.com/11452055/33607609-027dac08-d9c2-11e7-9498-3bb824742755.png)

Instead of gmx, use the uni-bremen webserver.

**Comment by ahaselsteiner** [comment]
@topape I think you are working on thie feature. Can you assign it to yourself?

**Comment by topape** [comment]
The issue was fixed in  'Resetting password: email confirmation link does not work #26'
