### ISSUE TITLE
Add doctests to travis

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#72]
The implemented doctests should be added to travis such that they are evaluated each time code is pushed to the repo.

**Comment by ahaselsteiner** [comment]
I am not too sure about this. However, we should discuss when we want to have doctests and when we want to have unittests.

**Comment by ahaselsteiner** [comment]
Result of team discussion:
* We add the doctests to travis
* As implement at the moment, coverage should only use the unittests (and not also the doctests)

**Comment by kawindme** [comment]
merged into ahaselsteiner/viroconcom#12
