### ISSUE TITLE
Change image of exponential dependency function

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#78]
The current displayed equation is incorrect (Exponential_PDF.png).

Instead of exp(x+c_2) it should be exp(x*c_2).

![image](https://user-images.githubusercontent.com/11452055/36098179-3b36447a-0ffe-11e8-80b9-0127a806299f.png)

**Comment by topape** [comment]
This issue was fixed in 'Use consistent style of graphics, add equations of probability density function #40'
