### ISSUE TITLE
Rethink purpose of package /enviro/compute/manual_tests.py

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#86]
What is the purpose of the manua_tests.py module? 

This should be thought together with doctests, untitests and travis integration.
Discuss this issue together with #72

**Comment by ahaselsteiner** [comment]
Result from team discussion:
It's not needed anymore and can be deleted

**Comment by kawindme** [comment]
moved to ahaselsteiner/viroconcom#7
