### ISSUE TITLE
Increase test coverage of fitting.py

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#89]
Important parts of the code of fitting.py are not covered by tests, or at least not by tests working with "python manage.py test", which is used with coverage and coveralls: https://coveralls.io/builds/15561940/source?filename=enviro/compute/fitting.py

Fitting.py is an important module and should be better covered. This issue might be related to #72 since maybe doctests already cover more of the module.

**Comment by kawindme** [comment]
moved to ahaselsteiner/viroconcom#12
